### PR TITLE
Add error handler for user.create

### PR DESCRIPTION
**Pull request by icebob**
Now it is handle the error and return a better error message with details.

image

### CODE REVIEW

**Comment by swyxio** [comment]
thanks for this fix. I have extended it a bit to provide required fields:
```javascript
					return user.save().catch(err => {
						if (err && err.code === 11000) {
							let field = err.message.split("index: ")[1];
							field = field.split(" dup key")[0];
							console.log('field',field);
							console.log('field.lastIndexOf',field.lastIndexOf("_"));
							field = field.substring(0, field.lastIndexOf("_"));				
							console.log('field',field);
							let newErr = new Error("Unable to save user!");
							newErr.params = {
								field: field,
							};
							newErr.msgCode = "DuplicateFieldError" + field;
							newErr.message = "Unable to save user, duplicate field " + field;
							newErr.type = "BAD_REQUEST";
							newErr.status = 400;
							throw newErr;
						}
						throw err;
					});
```

This still does not publish a nice message to `toastr.error` and I spent a couple of hours today trying to figure out why. 

## description of the problem
even though i send an error message with nicely formatted metadata:

image

The frontend only receives a short error message without any metadata:

```
Error: Request failed with status code 400
    at createError (createError.js:15)
    at settle (settle.js:19)
    at XMLHttpRequest.handleLoad (xhr.js:77)
```

the conclusion of my research is that we are fighting `axios`'s natural method of dealing with error codes. in `axios/lib/core/settle.js`, it actually STRIPS away the other metadata we provide in the response message and as far as i can tell this is the only thing that axios returns when we have a 400 error.

**Comment by swyxio** [comment]
ok i finally broke through. solution is to fix `modules/users/store/actions.js`. it is not compliant with the axios error handling api (https://github.com/mzabriskie/axios).

```js
export const saveRow = ({ commit }, model) => {
	axios.post(NAMESPACE, model).then((response) => {
		let res = response.data;
		if (res.status == 200 && res.data)
			created({ commit }, res.data, true);
	}).catch((err) => {
		//SWYX: changing based on https://github.com/mzabriskie/axios error handling
		const response = err.response;
		if (response.data.error)
			toastr.error(response.data.error.message);
	});		
};
```

image

**Comment by icebob** [comment]
I tried and it solves the problem:
```js
}).catch(({response}) => {
```

**Comment by icebob** [comment]
I'm seeing the code of other modules and it would be better if you use the [`service.rest`](https://github.com/icebob/vue-express-mongo-boilerplate/blob/ice-services/client/app/modules/posts/store/actions.js#L40) in vuex actions instead of direct axios. And it is handle error responses.

The code will be more simple:
```js
export const saveRow = function(store, model) {
	service.rest("create", model).then((data) => {
		created(store, data);
	}).catch((err) => {
		toastr.error(err.message);
	});
};
```

**Comment by swyxio** [comment]
ok great

**Comment by swyxio** [comment]
ok I refactored `client/app/modules/users/store/actions.js` to use `service.rest` and remove axios, everything is fine except for the "delete" action, because `service.rest` uses a `post` method and i really need to be sending using a `delete` method. To fix this i would need to modify `client/app/core/service.js` to take a new parameter but i didnt want to touch that core part of the code.

i have committed the refactor here:
https://github.com/sw-yx/vue-express-mongo-boilerplate/blob/ice-services/client/app/modules/users/store/actions.js#L64

**Comment by icebob** [comment]
Thank, I will check this `delete` issue.

**Comment by icebob** [comment]
Please use [this](https://github.com/sw-yx/vue-express-mongo-boilerplate/blob/ice-services/client/app/modules/posts/store/actions.js#L56) solution for delete.

```js
export const removeRow = function(store, model) {
	service.rest("remove", { code: model.code }).then((data) => {
		removed(store, data);
	}).catch((err) => {
		toastr.error(err.message);
	});
};
```

**Comment by swyxio** [comment]
ok sweet. I think we have a full functioning users module!!  pls have a look. https://github.com/sw-yx/vue-express-mongo-boilerplate/commit/b0f2d28944c9d2a59eb6a7b198463175dfa156e7  and the PR is here https://github.com/icebob/vue-express-mongo-boilerplate/pull/58

**Pull request merged**
